# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flashvsr.grpc.protos import ultraflashvsr_pb2 as flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flashvsr/grpc/protos/ultraflashvsr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UltraFlashVSRServiceStub(object):
    """---------------------------------------------------------------------------
    UltraFlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. StartSession  — allocates a fresh KV-cache for one video
    2. UpscaleChunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. EndSession    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    UpscaleVideo     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    GetStatus        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/ultraflashvsr.UltraFlashVSRService/GetStatus',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/ultraflashvsr.UltraFlashVSRService/StartSession',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/ultraflashvsr.UltraFlashVSRService/EndSession',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.UpscaleChunk = channel.unary_unary(
                '/ultraflashvsr.UltraFlashVSRService/UpscaleChunk',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.FromString,
                _registered_method=True)
        self.UpscaleVideo = channel.stream_stream(
                '/ultraflashvsr.UltraFlashVSRService/UpscaleVideo',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.FromString,
                _registered_method=True)


class UltraFlashVSRServiceServicer(object):
    """---------------------------------------------------------------------------
    UltraFlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. StartSession  — allocates a fresh KV-cache for one video
    2. UpscaleChunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. EndSession    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    UpscaleVideo     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    GetStatus        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpscaleChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpscaleVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UltraFlashVSRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionResponse.SerializeToString,
            ),
            'UpscaleChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.UpscaleChunk,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.SerializeToString,
            ),
            'UpscaleVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.UpscaleVideo,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ultraflashvsr.UltraFlashVSRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ultraflashvsr.UltraFlashVSRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UltraFlashVSRService(object):
    """---------------------------------------------------------------------------
    UltraFlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. StartSession  — allocates a fresh KV-cache for one video
    2. UpscaleChunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. EndSession    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    UpscaleVideo     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    GetStatus        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ultraflashvsr.UltraFlashVSRService/GetStatus',
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ultraflashvsr.UltraFlashVSRService/StartSession',
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ultraflashvsr.UltraFlashVSRService/EndSession',
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpscaleChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ultraflashvsr.UltraFlashVSRService/UpscaleChunk',
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpscaleVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ultraflashvsr.UltraFlashVSRService/UpscaleVideo',
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_ultraflashvsr__pb2.UpscaleChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
